[tool.poetry]
name = "FeedBackBot"
version = "0.1.0"
description = "Simple FeedBack Bot for the FL Studio discord server"
authors = [
    "killaxia",
    "dylanrenwick"
]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
discord = "^1.7.3"

[tool.poetry.dev-dependencies]
